services:
  xmltvguide:
    image: xmltvguide:latest
    container_name: xmltvguide
    ports:
      - "8586:80"
    restart: unless-stopped
    environment:
      # - EPG_URL=https://example.com/api/time={unixtime} - optional
      - EPG_URL_FILES=/app/epg_urls.txt # this or EPG_URL must be used to set the EPG source(s)
      - CHANNEL_MAP_PATH=/app/ChannelMap.json