services:
  xmltvguide:
    image: xmltvguide:latest
    container_name: xmltvguide
    ports:
      - "8586:80"
    restart: unless-stopped
    environment:
      - EPG_URL=https://tvlistings.gracenote.com/api/grid?lineupId=&timespan=6&headendId=CA04919&country=USA&timezone=&device=X&postalCode=90012&isOverride=true&time={unixtime}&pref=16%2C128&userId=-&aid=lat&languagecode=en-us
      - CHANNEL_MAP_PATH=/app/ChannelMap.json