services:
  xmltvguide:
    build: .
    image: xmltvguide:latest
    container_name: xmltvguide
    ports:
      - "8586:80"
    restart: unless-stopped
    environment:
      - RUN_AS_WEB=true
      - EPG_URL_FILES=/app/epg_urls.txt # this or EPG_URL must be used to set the EPG source(s)
      - CHANNEL_MAP_PATH=/app/ChannelMap.json
      - SETTINGS_PATH=/app/settings.json
      - USE_CHANNEL_NAMES_INSTEAD_OF_NUMERIC_IDS=${USE_CHANNEL_NAMES_INSTEAD_OF_NUMERIC_IDS:-}
      - SORT_CHANNELS_BY_ID=${SORT_CHANNELS_BY_ID:-}
      - OUTPUT_PATH=/app/output/guide.xml
      - CRONTAB_PATH=/etc/cron.d/epg-cron
      - AUTH_USERNAME=${AUTH_USERNAME:-admin}
      - AUTH_PASSWORD=${AUTH_PASSWORD:-changeme}
      - AUTH_EMAIL=${AUTH_EMAIL:-admin@xmltvguide.local}
    volumes:
      - ./epg_urls.txt:/app/epg_urls.txt
      - ./ChannelMap.json:/app/ChannelMap.json
      - ./settings.json:/app/settings.json
      - ./output:/app/output
      - ./logs:/app/logs
